export const actionTypes = {
    ADD_USER: 'ADD_USER',
    DELETE_USER: 'DELETE_USER',
    EDIT_USER: 'EDIT_USER',
    INVALIDATE_USERS: 'INVALIDATE_USERS',
    REQUEST_USERS: 'REQUEST_USERS',
    RECEIVE_USERS: 'RECEIVE_USERS',
    SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
    AUTHENTICATE: 'AUTHENTICATE',
}