export const actionTypes = {
  ADD_USER: "ADD_USER",
  DELETE_USER: "DELETE_USER",
  EDIT_USER: "EDIT_USER",
  INVALIDATE_USERS: "INVALIDATE_USERS",
  REQUEST_USERS: "REQUEST_USERS",
  RECEIVE_USERS: "RECEIVE_USERS",
  SET_VISIBILITY_FILTER: "SET_VISIBILITY_FILTER",
  // AUTHENTICATE: 'AUTHENTICATE',
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  ADMIN_REQUEST: "ADMIN_REQUEST",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  LOGOUT_REQUEST: "LOGOUT_REQUEST"
};
